# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fecha',
            name='fechaOpc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='idCuenta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='idCuentaPadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contapp.cuenta'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codEmpresa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='idFecha',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='idmovimiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partida',
            name='idPartida',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rubcuenta',
            name='idRubro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipcuenta',
            name='idTipo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
