# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0003_auto_20160925_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='idCuenta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contapp.cuenta'),
        ),
    ]
