# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0007_auto_20160926_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='idCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contapp.cuenta'),
        ),
    ]
