# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0009_auto_20160926_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='idCuenta',
        ),
    ]
