# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0011_movimiento_idcuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='idFecha',
        ),
        migrations.AddField(
            model_name='partida',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='fecha',
        ),
    ]
