# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 06:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0013_auto_20161001_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
