# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0015_auto_20161001_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='debe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='haber',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
