# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 22:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0016_auto_20161006_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='impArchivo',
            fields=[
                ('idImpArchivo', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='archivos')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('codEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contapp.empresa')),
            ],
        ),
    ]
