# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0017_imparchivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='nomCuenta',
            field=models.CharField(max_length=200),
        ),
    ]
