# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-12 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0018_auto_20161021_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='concepto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
